sudo: required

language: java

jdk:
  - oraclejdk8

services:
  - docker

script:
  # - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # - docker build -t perfectcomputersolutions/pos .
  # - docker run -d -p 8080:80 perfectcomputersolutions/pos
  - cd src/server
  - ./gradlew test -i
  - ./gradlew clean build
  - docker-compose up --build -d
  - sleep 10
  - docker ps -a
  - curl localhost:4200
  - curl localhost:8080/user

after_success:
    - docker-compose down
#   - docker push perfectcomputersolutions/pos

on:
  branch: master

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
