sudo: required

services:
  - docker

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t perfectcomputersolutions/pos .
  - docker run -d -p 8080:80 perfectcomputersolutions/pos
  - sleep 5
  - docker ps -a
  - curl localhost:80

after_success:
  - docker push perfectcomputersolutions/pos

on:
  branch: master
