sudo: required

language: java

jdk:
  - oraclejdk8

services:
  - docker

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - ./ci/database.sh
  - ./ci/server.sh
  - ./ci/client.sh

after_success:
  - ./ci/upload.sh

# TODO - cache node_module for client code to decrease build time

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
