sudo: required

language: java

jdk:
  - oraclejdk8

on:
  branch: master

services:
  - docker

script:
  # - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - ./ci/travis.sh

after_success:
    - docker ps -a
#   - docker push perfectcomputersolutions/pos

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
