insert ignore into category (name) values
('Nantucket Orange Juice'),
('Wine - Fontanafredda Barolo'),
('Lid Tray - 16in Dome'),
('Salmon Steak - Cohoe 8 Oz'),
('Bacardi Limon'),
('Lid - High Heat, Super Clear'),
('Silicone Paper 16.5x24'),
('Table Cloth 54x72 White'),
('Beef - Rib Roast, Capless'),
('Rambutan'),
('Eggs - Extra Large'),
('Bag Clear 10 Lb'),
('Meldea Green Tea Liquor'),
('Higashimaru Usukuchi Soy'),
('Wine - Gewurztraminer Pierre'),
('Bread - Kimel Stick Poly'),
('Puree - Passion Fruit'),
('Cheese - Swiss Sliced'),
('Steel Wool S.o.s'),
('Coffee - Decaffeinato Coffee'),
('Curry Paste - Madras'),
('Lotus Leaves'),
('Chicken - Wings, Tip Off'),
('Tart - Raisin And Pecan'),
('Tomatoes - Hot House'),
('Mackerel Whole Fresh'),
('Lettuce - Lambs Mash'),
('Chocolate - Semi Sweet, Calets'),
('Cheese - Cheddar With Claret'),
('Samosa - Veg'),
('Wine - Vidal Icewine Magnotta'),
('Nut - Almond, Blanched, Whole'),
('Turnip - Wax'),
('Pineapple - Regular'),
('Oil - Truffle, Black'),
('Veal - Loin'),
('Wine - White, Chardonnay'),
('Peas - Pigeon, Dry'),
('Wine - German Riesling'),
('Bread - Pumpernickel'),
('Brandy - Bar'),
('Oil - Truffle, Black'),
('Vermouth - Sweet, Cinzano'),
('Cotton Wet Mop 16 Oz'),
('Pork - Chop, Frenched'),
('Allspice - Jamaican'),
('Breadfruit'),
('Wine - Magnotta - Red, Baco'),
('Tuna - Fresh'),
('Bread - Sour Sticks With Onion'),
('Wine - Pinot Grigio Collavini'),
('Chutney Sauce - Mango'),
('Oregano - Dry, Rubbed'),
('Garlic - Elephant'),
('Steel Wool'),
('Longos - Penne With Pesto'),
('Muffin Batt - Carrot Spice'),
('Appetizer - Cheese Bites'),
('Orange - Canned, Mandarin'),
('Crackers - Graham'),
('Capers - Ox Eye Daisy'),
('Coffee - Decafenated'),
('Veal - Insides Provini'),
('Puree - Blackcurrant'),
('Wine - Red, Wolf Blass, Yellow'),
('Milk - 1%'),
('Sloe Gin - Mcguinness'),
('Carbonated Water - Orange'),
('Rum - Spiced, Captain Morgan'),
('Lidsoupcont Rp12dn'),
('Milk - Chocolate 250 Ml'),
('Herb Du Provence - Primerba'),
('Bacardi Breezer - Tropical'),
('Salt And Pepper Mix - Black'),
('Gelatine Leaves - Envelopes'),
('Cheese - Goat With Herbs'),
('Basil - Fresh'),
('Tomato - Tricolor Cherry'),
('Vinegar - Balsamic, White'),
('Tea - Jasmin Green'),
('Pork - Back, Long Cut, Boneless'),
('Pasta - Cheese / Spinach Bauletti'),
('Pork - Tenderloin, Frozen'),
('Wine - Blue Nun Qualitatswein'),
('Soap - Pine Sol Floor Cleaner'),
('Ice Cream Bar - Rolo Cone'),
('Pasta - Cappellini, Dry'),
('Pie Filling - Apple'),
('Pea - Snow'),
('Soup - Cream Of Broccoli, Dry'),
('Wine - White, Ej Gallo'),
('Absolut Citron'),
('Lamb - Shoulder, Boneless'),
('Sour Cream'),
('Rice Wine - Aji Mirin'),
('Table Cloth 54x54 White'),
('Cheese - Mascarpone'),
('Bread - Italian Sesame Poly'),
('Apples - Sliced / Wedge'),
('Wine - Alsace Riesling Reserve'),
('Lemonade - Kiwi, 591 Ml'),
('Beer - Original Organic Lager'),
('Olive - Spread Tapenade'),
('V8 - Vegetable Cocktail'),
('Wine - Magnotta - Cab Sauv'),
('Wiberg Super Cure'),
('Cup - 3.5oz, Foam'),
('Wine - Chenin Blanc K.w.v.'),
('Wine - White, Riesling, Semi - Dry'),
('Wine - White, Riesling, Henry Of'),
('Cheese - Le Cheve Noir'),
('Sauce - Salsa'),
('Cheese - Swiss Sliced'),
('Cup - 4oz Translucent'),
('Wine - Carmenere Casillero Del'),
('Filo Dough'),
('Pumpkin'),
('Kiwi'),
('Shiratamako - Rice Flour'),
('Mix - Cocktail Strawberry Daiquiri'),
('Lemonade - Strawberry, 591 Ml'),
('Veal Inside - Provimi'),
('Wine - Bouchard La Vignee Pinot'),
('Lettuce - Boston Bib - Organic'),
('Bar Mix - Lime'),
('Quiche Assorted'),
('Beans - Fava Fresh'),
('Shark - Loin'),
('Vinegar - Sherry'),
('Bonito Flakes - Toku Katsuo'),
('Rosemary - Primerba, Paste'),
('Plums - Red'),
('Lamb - Racks, Frenched'),
('Pear - Prickly'),
('Mushroom - Portebello'),
('Compound - Passion Fruit'),
('Wine - White, Gewurtzraminer'),
('Pork - Bacon Cooked Slcd'),
('Pepper - Paprika, Hungarian'),
('Chick Peas - Dried'),
('Pepper - Red Thai'),
('Shrimp - Black Tiger 8 - 12'),
('Sachet'),
('Pail - 15l White, With Handle'),
('Pork - Back, Long Cut, Boneless'),
('Yogurt - Assorted Pack'),
('Beef - Roasted, Cooked'),
('Muffin - Banana Nut Individual'),
('Bread - Italian Corn Meal Poly'),
('Southern Comfort'),
('Cheese - Parmesan Cubes'),
('Glucose'),
('Puree - Passion Fruit'),
('Compound - Raspberry'),
('Worcestershire Sauce'),
('Soup - Verve - Chipotle Chicken'),
('Pork - Sausage, Medium'),
('Barramundi'),
('Wine - Casillero Del Diablo'),
('Mint - Fresh'),
('Salami - Genova'),
('Glove - Cutting'),
('Smoked Tongue'),
('Tomatoes - Heirloom'),
('Soupfoamcont12oz 112con'),
('Sponge Cake Mix - Vanilla'),
('Chicken - Livers'),
('Spice - Montreal Steak Spice'),
('Soup - Campbells - Chicken Noodle'),
('Olives - Kalamata'),
('Bar - Sweet And Salty Chocolate'),
('Dragon Fruit'),
('Burger Veggie'),
('Doilies - 10, Paper'),
('Pepper - Black, Whole'),
('Grouper - Fresh'),
('Neckerchief Blck'),
('Bread - Italian Corn Meal Poly'),
('Towel Dispenser'),
('Cheese - Brick With Onion'),
('Turnip - White'),
('Uniform Linen Charge'),
('Wine - White, Riesling, Henry Of'),
('Pork - Loin, Bone - In'),
('Langers - Cranberry Cocktail'),
('Rye Special Old'),
('Beef - Short Ribs'),
('Bread Fig And Almond'),
('Bread - Rye'),
('Beer - True North Lager'),
('Muffin Batt - Carrot Spice'),
('Orange - Canned, Mandarin'),
('Chocolate - Dark Callets'),
('Beans - Wax'),
('Soup - Campbells - Chicken Noodle'),
('Veal - Chops, Split, Frenched'),
('Cheese - Parmesan Grated'),
('Mushroom - Portebello'),
('Vinegar - Balsamic, White'),
('Mix - Cocktail Strawberry Daiquiri');
